#!/usr/bin/env bash

main() {
  build
}

build() {
  echo ">> Building ..."
  #NODE_ENV=production webpack
  babel --presets es2015 src/dens.js > build/dens.js
}

case "$1" in
  "" ) main ;;
  b | build ) build ;;
esac
