#!/usr/bin/env bash

main() {
  build
}

build() {
  echo ">> Building ..."
  #NODE_ENV=production webpack
  babel --presets es2015 src -d build
}

case "$1" in
  "" ) main ;;
  b | build ) build ;;
esac
